#include "nigiri/visualize_timetable.h"

#include <algorithm>
#include <cmath>
#include <iomanip>
#include <ostream>
#include <string>
#include <vector>

namespace nigiri {
namespace {

struct point {
  double x_;
  double y_;
};

std::vector<point> get_points(timetable const& tt) {
  auto points = std::vector<point>{};
  points.reserve(tt.n_locations());
  for (auto l = location_idx_t{0U}; l < tt.n_locations(); ++l) {
    auto const& coordinate = tt.locations_.coordinates_[l];
    points.push_back({coordinate.lng(), coordinate.lat()});
  }
  return points;
}

void write_svg(std::ostream& out, std::vector<point> const& points,
               timetable_visualization_options const& options) {
  auto min_x = points.front().x_;
  auto max_x = min_x;
  auto min_y = points.front().y_;
  auto max_y = min_y;
  for (auto const p : points) {
    min_x = std::min(min_x, p.x_);
    max_x = std::max(max_x, p.x_);
    min_y = std::min(min_y, p.y_);
    max_y = std::max(max_y, p.y_);
  }
  auto const x_span = std::max(max_x - min_x, 1e-9);
  auto const y_span = std::max(max_y - min_y, 1e-9);
  auto const padding = options.padding_ * std::max(x_span, y_span);
  min_x -= padding;
  max_x += padding;
  min_y -= padding;
  max_y += padding;
  auto const height = options.width_ * (max_y - min_y) / (max_x - min_x);

  out << std::setprecision(12)
      << "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"" << options.width_
      << "\" height=\"" << height << "\" viewBox=\"0 0 " << options.width_
      << ' ' << height << "\" preserveAspectRatio=\"none\">\n";
  if (options.background_) {
    out << "  <rect width=\"100%\" height=\"100%\" fill=\"#f4ecd8\"/>\n";
  }
  auto const scale = options.width_ / (max_x - min_x);
  auto const radius = options.point_radius_ * scale;
  out << "  <g fill=\"#594538\">\n";
  for (auto const p : points) {
    auto const x = (p.x_ - min_x) * scale;
    auto const y = (max_y - p.y_) * scale;
    out << "    <circle cx=\"" << x << "\" cy=\"" << y
        << "\" r=\"" << radius << "\"/>\n";
  }
  out << "  </g>\n</svg>\n";
}

void write_tikz(std::ostream& out, std::vector<point> const& points,
                timetable_visualization_options const& options) {
  auto min_x = points.front().x_;
  auto max_x = min_x;
  auto min_y = points.front().y_;
  auto max_y = min_y;
  for (auto const p : points) {
    min_x = std::min(min_x, p.x_);
    max_x = std::max(max_x, p.x_);
    min_y = std::min(min_y, p.y_);
    max_y = std::max(max_y, p.y_);
  }
  auto const x_span = std::max(max_x - min_x, 1e-9);
  auto const y_span = std::max(max_y - min_y, 1e-9);
  auto const padding = options.padding_ * std::max(x_span, y_span);
  min_x -= padding;
  max_x += padding;
  min_y -= padding;
  max_y += padding;
  auto const height_cm = 10.0 * (max_y - min_y) / (max_x - min_x);
  auto const radius = options.point_radius_ * 10.0 / (max_x - min_x);

  out << "% Generated by nigiri-para visualize-timetable\n"
      << "\\begin{tikzpicture}[x=10cm/" << (max_x - min_x)
      << ",y=10cm/" << (max_x - min_x) << "]\n";
  if (options.background_) {
    out << "  \\fill[fill={rgb,1:red,0.957;green,0.925;blue,0.847}] ("
        << min_x << ',' << min_y << ") rectangle (" << max_x << ',' << max_y
        << ");\n";
  }
  out << "  \\begin{scope}[fill={rgb,1:red,0.349;green,0.271;blue,0.220}]\n";
  for (auto const p : points) {
    out << "    \\fill (" << p.x_ << ',' << p.y_ << ") circle (" << radius
        << "cm);\n";
  }
  out << "  \\end{scope}\n\\end{tikzpicture}\n"
      << "% Bounding box: " << (max_x - min_x) << " x " << height_cm
      << " degrees\n";
}

}  // namespace

void visualize_timetable(timetable const& tt, std::ostream& out,
                         timetable_visualization_options const& options) {
  auto const points = get_points(tt);
  if (points.empty()) {
    return;
  }
  if (options.format_ == timetable_visualization_format::kTikz) {
    write_tikz(out, points, options);
  } else {
    write_svg(out, points, options);
  }
}

}  // namespace nigiri
